// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nztvlyjfeilityxoygdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dHZseWpmZWlsaXR5eG95Z2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQyMjMyMjQsImV4cCI6MjA3OTc5OTIyNH0.DTKEhxPD12-wP8VH4HpYlFukxf6PvBw9Khj3ncS5SSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});